project:
  type: book
  output-dir: docs
book:
  title: AQUA-d Forum
  subtitle: Sitzung 04 - Regression 01
  author: Samuel Merk
  chapters:
  - index.qmd
  - regression.qmd
  - regression_assumptions.qmd
  - regression_with_dummies.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    fontsize: .8em
lang: de
lightbox: false
